//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IClient {

    /**
     * Dump Resolver data
     * @return OK
     */
    resolvers(signal?: AbortSignal): Promise<void>;

    /**
     * Get database zones
     * @return OK
     */
    zonesGET(signal?: AbortSignal): Promise<void>;

    /**
     * Get database zones
     * @param body (optional) 
     * @return OK
     */
    zonesPUT(body: ZoneDto | undefined, signal?: AbortSignal): Promise<void>;

    /**
     * Get database zones
     * @param body (optional) 
     * @return OK
     */
    zonesPATCH(body: ZoneDto | undefined, signal?: AbortSignal): Promise<void>;

    /**
     * Delete database zone
     * @param id Zone identifier.
     * @return No Content
     */
    zonesDELETE(id: number, signal?: AbortSignal): Promise<void>;

    /**
     * Import a BIND zone file into the database-backed zone model.
     * @param body (optional) Import settings.
     * @return OK
     */
    importBind(body: BindZoneImportRequest | undefined, signal?: AbortSignal): Promise<void>;

    /**
     * Import all currently active BIND zones into database zones and disable those BIND providers at runtime.
     * @param body (optional) Bulk import settings.
     * @return OK
     */
    importActiveBind(body: ActiveBindImportRequest | undefined, signal?: AbortSignal): Promise<void>;

    /**
     * Dump Resolver data
     * @return OK
     * @deprecated
     */
    dnsresolver(signal?: AbortSignal): Promise<void>;

    /**
     * Dump DnsServer data
     * @return OK
     * @deprecated
     */
    dnsserver(signal?: AbortSignal): Promise<void>;

    /**
     * Get current user
     * @return OK
     */
    user(signal?: AbortSignal): Promise<UserDto>;

    /**
     * Log in
     * @param body (optional) 
     * @return OK
     */
    loginPOST(body: LoginRequest | undefined, signal?: AbortSignal): Promise<string>;

    /**
     * Log in
     * @param account (optional) 
     * @param password (optional) 
     * @return OK
     */
    loginGET(account: string | undefined, password: string | undefined, signal?: AbortSignal): Promise<string>;
}

export class Client implements IClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Dump Resolver data
     * @return OK
     */
    resolvers(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/resolvers";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processResolvers(_response);
        });
    }

    protected processResolvers(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get database zones
     * @return OK
     */
    zonesGET(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/zones";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processZonesGET(_response);
        });
    }

    protected processZonesGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get database zones
     * @param body (optional) 
     * @return OK
     */
    zonesPUT(body: ZoneDto | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/zones";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processZonesPUT(_response);
        });
    }

    protected processZonesPUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get database zones
     * @param body (optional) 
     * @return OK
     */
    zonesPATCH(body: ZoneDto | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/zones";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processZonesPATCH(_response);
        });
    }

    protected processZonesPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Delete database zone
     * @param id Zone identifier.
     * @return No Content
     */
    zonesDELETE(id: number, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/zones/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processZonesDELETE(_response);
        });
    }

    protected processZonesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Import a BIND zone file into the database-backed zone model.
     * @param body (optional) Import settings.
     * @return OK
     */
    importBind(body: BindZoneImportRequest | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/zones/import-bind";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processImportBind(_response);
        });
    }

    protected processImportBind(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Import all currently active BIND zones into database zones and disable those BIND providers at runtime.
     * @param body (optional) Bulk import settings.
     * @return OK
     */
    importActiveBind(body: ActiveBindImportRequest | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dns/zones/import-active-bind";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processImportActiveBind(_response);
        });
    }

    protected processImportActiveBind(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Dump Resolver data
     * @return OK
     * @deprecated
     */
    dnsresolver(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dump/dnsresolver";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDnsresolver(_response);
        });
    }

    protected processDnsresolver(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Dump DnsServer data
     * @return OK
     * @deprecated
     */
    dnsserver(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/dump/dnsserver";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDnsserver(_response);
        });
    }

    protected processDnsserver(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get current user
     * @return OK
     */
    user(signal?: AbortSignal): Promise<UserDto> {
        let url_ = this.baseUrl + "/user";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUser(_response);
        });
    }

    protected processUser(response: Response): Promise<UserDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result200 = UserDto.fromJS(resultData200, _mappings);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404, _mappings);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserDto>(null as any);
    }

    /**
     * Log in
     * @param body (optional) 
     * @return OK
     */
    loginPOST(body: LoginRequest | undefined, signal?: AbortSignal): Promise<string> {
        let url_ = this.baseUrl + "/user/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLoginPOST(_response);
        });
    }

    protected processLoginPOST(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * Log in
     * @param account (optional) 
     * @param password (optional) 
     * @return OK
     */
    loginGET(account: string | undefined, password: string | undefined, signal?: AbortSignal): Promise<string> {
        let url_ = this.baseUrl + "/user/login?";
        if (account === null)
            throw new globalThis.Error("The parameter 'account' cannot be null.");
        else if (account !== undefined)
            url_ += "account=" + encodeURIComponent("" + account) + "&";
        if (password === null)
            throw new globalThis.Error("The parameter 'password' cannot be null.");
        else if (password !== undefined)
            url_ += "password=" + encodeURIComponent("" + password) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLoginGET(_response);
        });
    }

    protected processLoginGET(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        let _mappings: { source: any, target: any }[] = [];
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : jsonParse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400, _mappings);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }
}

/** Options controlling the bulk import of active BIND zones into database-backed zones. */
export class ActiveBindImportRequest implements IActiveBindImportRequest {
    /** Replaces existing database records for each imported zone suffix when true. */
    replaceExistingRecords?: boolean;
    /** Sets imported database zones to enabled when true. */
    enableImportedZones?: boolean;

    constructor(data?: IActiveBindImportRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            this.replaceExistingRecords = _data["replaceExistingRecords"] !== undefined ? _data["replaceExistingRecords"] : null as any;
            this.enableImportedZones = _data["enableImportedZones"] !== undefined ? _data["enableImportedZones"] : null as any;
        }
    }

    static fromJS(data: any, _mappings?: any): ActiveBindImportRequest | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<ActiveBindImportRequest>(data, _mappings, ActiveBindImportRequest);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["replaceExistingRecords"] = this.replaceExistingRecords !== undefined ? this.replaceExistingRecords : null as any;
        data["enableImportedZones"] = this.enableImportedZones !== undefined ? this.enableImportedZones : null as any;
        return data;
    }
}

/** Options controlling the bulk import of active BIND zones into database-backed zones. */
export interface IActiveBindImportRequest {
    /** Replaces existing database records for each imported zone suffix when true. */
    replaceExistingRecords?: boolean;
    /** Sets imported database zones to enabled when true. */
    enableImportedZones?: boolean;
}

/** Request body for importing a single BIND zone file into a database-backed zone. */
export class BindZoneImportRequest implements IBindZoneImportRequest {
    /** Absolute or relative path to the BIND zone file. */
    fileName!: string;
    /** Zone suffix to use as the database zone key (for example, "example.com"). */
    zoneSuffix!: string;
    /** Marks the imported database zone as enabled when true. */
    enabled?: boolean;
    /** Replaces existing database records for the same zone suffix when true. */
    replaceExistingRecords?: boolean;

    constructor(data?: IBindZoneImportRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            this.fileName = _data["fileName"] !== undefined ? _data["fileName"] : null as any;
            this.zoneSuffix = _data["zoneSuffix"] !== undefined ? _data["zoneSuffix"] : null as any;
            this.enabled = _data["enabled"] !== undefined ? _data["enabled"] : null as any;
            this.replaceExistingRecords = _data["replaceExistingRecords"] !== undefined ? _data["replaceExistingRecords"] : null as any;
        }
    }

    static fromJS(data: any, _mappings?: any): BindZoneImportRequest | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<BindZoneImportRequest>(data, _mappings, BindZoneImportRequest);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fileName"] = this.fileName !== undefined ? this.fileName : null as any;
        data["zoneSuffix"] = this.zoneSuffix !== undefined ? this.zoneSuffix : null as any;
        data["enabled"] = this.enabled !== undefined ? this.enabled : null as any;
        data["replaceExistingRecords"] = this.replaceExistingRecords !== undefined ? this.replaceExistingRecords : null as any;
        return data;
    }
}

/** Request body for importing a single BIND zone file into a database-backed zone. */
export interface IBindZoneImportRequest {
    /** Absolute or relative path to the BIND zone file. */
    fileName: string;
    /** Zone suffix to use as the database zone key (for example, "example.com"). */
    zoneSuffix: string;
    /** Marks the imported database zone as enabled when true. */
    enabled?: boolean;
    /** Replaces existing database records for the same zone suffix when true. */
    replaceExistingRecords?: boolean;
}

export class LoginRequest implements ILoginRequest {
    account?: string | null;
    password?: string | null;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            this.account = _data["account"] !== undefined ? _data["account"] : null as any;
            this.password = _data["password"] !== undefined ? _data["password"] : null as any;
        }
    }

    static fromJS(data: any, _mappings?: any): LoginRequest | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<LoginRequest>(data, _mappings, LoginRequest);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["account"] = this.account !== undefined ? this.account : null as any;
        data["password"] = this.password !== undefined ? this.password : null as any;
        return data;
    }
}

export interface ILoginRequest {
    account?: string | null;
    password?: string | null;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"] !== undefined ? _data["type"] : null as any;
            this.title = _data["title"] !== undefined ? _data["title"] : null as any;
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
            this.detail = _data["detail"] !== undefined ? _data["detail"] : null as any;
            this.instance = _data["instance"] !== undefined ? _data["instance"] : null as any;
        }
    }

    static fromJS(data: any, _mappings?: any): ProblemDetails | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<ProblemDetails>(data, _mappings, ProblemDetails);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type !== undefined ? this.type : null as any;
        data["title"] = this.title !== undefined ? this.title : null as any;
        data["status"] = this.status !== undefined ? this.status : null as any;
        data["detail"] = this.detail !== undefined ? this.detail : null as any;
        data["instance"] = this.instance !== undefined ? this.instance : null as any;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;

    [key: string]: any;
}

export enum ResourceClass {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

export enum ResourceType {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
    _7 = 7,
    _8 = 8,
    _9 = 9,
    _10 = 10,
    _11 = 11,
    _12 = 12,
    _13 = 13,
    _14 = 14,
    _15 = 15,
    _16 = 16,
    _17 = 17,
    _18 = 18,
    _19 = 19,
    _20 = 20,
    _21 = 21,
    _22 = 22,
    _23 = 23,
    _24 = 24,
    _25 = 25,
    _26 = 26,
    _27 = 27,
    _28 = 28,
    _29 = 29,
    _30 = 30,
    _31 = 31,
    _32 = 32,
    _33 = 33,
    _34 = 34,
    _35 = 35,
    _36 = 36,
    _37 = 37,
    _38 = 38,
    _39 = 39,
    _40 = 40,
    _41 = 41,
    _43 = 43,
    _46 = 46,
    _47 = 47,
    _48 = 48,
    _49 = 49,
    _100 = 100,
    _101 = 101,
    _102 = 102,
    _103 = 103,
    _248 = 248,
    _249 = 249,
    _250 = 250,
    _251 = 251,
    _252 = 252,
    _253 = 253,
    _254 = 254,
    _255 = 255,
    _65281 = 65281,
    _65282 = 65282,
}

/** API representation of an authenticated user. */
export class UserDto implements IUserDto {
    /** User identifier. */
    id?: number;
    /** Account username. */
    account?: string | null;
    /** Indicates whether the account is activated. */
    activated?: boolean;
    /** Administrative level for the user. */
    adminLevel?: number;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            this.id = _data["id"] !== undefined ? _data["id"] : null as any;
            this.account = _data["account"] !== undefined ? _data["account"] : null as any;
            this.activated = _data["activated"] !== undefined ? _data["activated"] : null as any;
            this.adminLevel = _data["adminLevel"] !== undefined ? _data["adminLevel"] : null as any;
        }
    }

    static fromJS(data: any, _mappings?: any): UserDto | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<UserDto>(data, _mappings, UserDto);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : null as any;
        data["account"] = this.account !== undefined ? this.account : null as any;
        data["activated"] = this.activated !== undefined ? this.activated : null as any;
        data["adminLevel"] = this.adminLevel !== undefined ? this.adminLevel : null as any;
        return data;
    }
}

/** API representation of an authenticated user. */
export interface IUserDto {
    /** User identifier. */
    id?: number;
    /** Account username. */
    account?: string | null;
    /** Indicates whether the account is activated. */
    activated?: boolean;
    /** Administrative level for the user. */
    adminLevel?: number;
}

/** API representation of a DNS zone. */
export class ZoneDto implements IZoneDto {
    /** Zone identifier. */
    id?: number | null;
    /** Authoritative suffix for the zone. */
    suffix?: string | null;
    /** Zone serial. */
    serial?: number;
    /** Indicates whether the zone is active. */
    enabled?: boolean;
    /** Optional master zone identifier when this zone is configured as a slave. */
    masterZoneId?: number | null;
    /** Master zone suffix for overview display. */
    masterZoneSuffix?: string | null;
    /** Number of slave zones linked to this zone. */
    slaveZoneCount?: number;
    /** Zone records. */
    records?: ZoneRecordDto[] | null;

    constructor(data?: IZoneDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            this.id = _data["id"] !== undefined ? _data["id"] : null as any;
            this.suffix = _data["suffix"] !== undefined ? _data["suffix"] : null as any;
            this.serial = _data["serial"] !== undefined ? _data["serial"] : null as any;
            this.enabled = _data["enabled"] !== undefined ? _data["enabled"] : null as any;
            this.masterZoneId = _data["masterZoneId"] !== undefined ? _data["masterZoneId"] : null as any;
            this.masterZoneSuffix = _data["masterZoneSuffix"] !== undefined ? _data["masterZoneSuffix"] : null as any;
            this.slaveZoneCount = _data["slaveZoneCount"] !== undefined ? _data["slaveZoneCount"] : null as any;
            if (Array.isArray(_data["records"])) {
                this.records = [] as any;
                for (let item of _data["records"])
                    this.records!.push(ZoneRecordDto.fromJS(item, _mappings));
            }
            else {
                this.records = null as any;
            }
        }
    }

    static fromJS(data: any, _mappings?: any): ZoneDto | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<ZoneDto>(data, _mappings, ZoneDto);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : null as any;
        data["suffix"] = this.suffix !== undefined ? this.suffix : null as any;
        data["serial"] = this.serial !== undefined ? this.serial : null as any;
        data["enabled"] = this.enabled !== undefined ? this.enabled : null as any;
        data["masterZoneId"] = this.masterZoneId !== undefined ? this.masterZoneId : null as any;
        data["masterZoneSuffix"] = this.masterZoneSuffix !== undefined ? this.masterZoneSuffix : null as any;
        data["slaveZoneCount"] = this.slaveZoneCount !== undefined ? this.slaveZoneCount : null as any;
        if (Array.isArray(this.records)) {
            data["records"] = [];
            for (let item of this.records)
                data["records"].push(item ? item.toJSON() : null as any);
        }
        return data;
    }
}

/** API representation of a DNS zone. */
export interface IZoneDto {
    /** Zone identifier. */
    id?: number | null;
    /** Authoritative suffix for the zone. */
    suffix?: string | null;
    /** Zone serial. */
    serial?: number;
    /** Indicates whether the zone is active. */
    enabled?: boolean;
    /** Optional master zone identifier when this zone is configured as a slave. */
    masterZoneId?: number | null;
    /** Master zone suffix for overview display. */
    masterZoneSuffix?: string | null;
    /** Number of slave zones linked to this zone. */
    slaveZoneCount?: number;
    /** Zone records. */
    records?: ZoneRecordDto[] | null;
}

/** API representation of a DNS zone record. */
export class ZoneRecordDto implements IZoneRecordDto {
    /** Zone record identifier. */
    id?: number | null;
    /** Host label of the record. */
    host?: string | null;
    class?: ResourceClass;
    type?: ResourceType;
    /** Record payload, e.g. IP address or canonical name. */
    data?: string | null;
    /** Parent zone identifier. */
    zone?: number | null;

    constructor(data?: IZoneRecordDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any, _mappings?: any) {
        if (_data) {
            this.id = _data["id"] !== undefined ? _data["id"] : null as any;
            this.host = _data["host"] !== undefined ? _data["host"] : null as any;
            this.class = _data["class"] !== undefined ? _data["class"] : null as any;
            this.type = _data["type"] !== undefined ? _data["type"] : null as any;
            this.data = _data["data"] !== undefined ? _data["data"] : null as any;
            this.zone = _data["zone"] !== undefined ? _data["zone"] : null as any;
        }
    }

    static fromJS(data: any, _mappings?: any): ZoneRecordDto | null {
        data = typeof data === 'object' ? data : {};
        return createInstance<ZoneRecordDto>(data, _mappings, ZoneRecordDto);
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : null as any;
        data["host"] = this.host !== undefined ? this.host : null as any;
        data["class"] = this.class !== undefined ? this.class : null as any;
        data["type"] = this.type !== undefined ? this.type : null as any;
        data["data"] = this.data !== undefined ? this.data : null as any;
        data["zone"] = this.zone !== undefined ? this.zone : null as any;
        return data;
    }
}

/** API representation of a DNS zone record. */
export interface IZoneRecordDto {
    /** Zone record identifier. */
    id?: number | null;
    /** Host label of the record. */
    host?: string | null;
    class?: ResourceClass;
    type?: ResourceType;
    /** Record payload, e.g. IP address or canonical name. */
    data?: string | null;
    /** Parent zone identifier. */
    zone?: number | null;
}

function jsonParse(json: any, reviver?: any) {
    json = JSON.parse(json, reviver);

    var byid: any = {};
    var refs: any = [];
    json = (function recurse(obj: any, prop?: any, parent?: any) {
        if (typeof obj !== 'object' || !obj)
            return obj;
        
        if ("$ref" in obj) {
            let ref = obj.$ref;
            if (ref in byid)
                return byid[ref];
            refs.push([parent, prop, ref]);
            return undefined;
        } else if ("$id" in obj) {
            let id = obj.$id;
            delete obj.$id;
            if ("$values" in obj)
                obj = obj.$values;
            byid[id] = obj;
        }
        
        if (Array.isArray(obj)) {
            obj = obj.map((v, i) => recurse(v, i, obj));
        } else {
            for (var p in obj) {
                if (obj.hasOwnProperty(p) && obj[p] && typeof obj[p] === 'object')
                    obj[p] = recurse(obj[p], p, obj);
            }
        }

        return obj;
    })(json);

    for (let i = 0; i < refs.length; i++) {
        const ref = refs[i];
        ref[0][ref[1]] = byid[ref[2]];
    }

    return json;
}

function createInstance<T>(data: any, mappings: any, type: any): T | null {
  if (!mappings)
    mappings = [];
  if (!data)
    return null;

  const mappingIndexName = "__mappingIndex";
  if (data[mappingIndexName])
    return <T>mappings[data[mappingIndexName]].target;

  data[mappingIndexName] = mappings.length;

  let result: any = new type();
  mappings.push({ source: data, target: result });
  result.init(data, mappings);
  return result;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}