// <auto-generated />

using Dns.Db.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dns.Cli.Migrations
{
    [DbContext(typeof(DnsServerDbContext))]
    [Migration("20251011113400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Dns.Cli.Models.EntityFramework.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<bool>("Activated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activated");

                    b.Property<byte>("AdminLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adminlevel");

                    b.Property<string>("Password")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("salt");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}