// <auto-generated />

#nullable disable

using Dns.Db.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Dns.Cli.Migrations
{
    [DbContext(typeof(DnsServerDbContext))]
    [Migration("20251012131553_Rev2")]
    partial class Rev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Dns.Db.Models.EntityFramework.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<bool>("Activated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activated");

                    b.Property<byte>("AdminLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adminlevel");

                    b.Property<string>("Password")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("salt");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Dns.Db.Models.EntityFramework.Zone", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<uint>("Serial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("serial");

                    b.Property<string>("Suffix")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("suffix");

                    b.HasKey("Id");

                    b.HasIndex("Suffix")
                        .IsUnique();

                    b.ToTable("zones");
                });

            modelBuilder.Entity("Dns.Db.Models.EntityFramework.ZoneRecord", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ushort?>("Class")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Host")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<ushort?>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<int?>("Zone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("Zone");

                    b.ToTable("zone_records");
                });

            modelBuilder.Entity("Dns.Db.Models.EntityFramework.ZoneRecord", b =>
                {
                    b.HasOne("Dns.Db.Models.EntityFramework.Zone", "ZoneObj")
                        .WithMany("Records")
                        .HasForeignKey("Zone")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ZoneObj");
                });

            modelBuilder.Entity("Dns.Db.Models.EntityFramework.Zone", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
